### ISSUE TITLE
Does not autoload rails environment

### ISSUE THREAD

**Issue by KMarshland** [dazuma/toys#2]
When writing a toys file, it does not have access to all of the files that typically get autoloaded by rails. In rake, you can do something like `task :generate, [:mission_name] => [:environment] do |_task, args|`, but there doesn't appear to be anything similar in the toys documentation.

Log:
```
NameError: uninitialized constant Mission
     22: /Users/kai/.rbenv/versions/2.6.3/bin/toys:23:in `<main>'
     21: /Users/kai/.rbenv/versions/2.6.3/bin/toys:23:in `load'
     20: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-0.8.0/bin/toys:30:in `<top (required)>'
     19: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:399:in `run'
     18: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/errors.rb:91:in `capture_path'
     17: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:403:in `block in run'
     16: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:432:in `run_tool'
     15: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:456:in `perform_execution'
     14: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:456:in `catch'
     13: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:457:in `block in perform_execution'
     12: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:487:in `block in make_executor'
     11: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/middleware.rb:90:in `run'
     10: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:487:in `block in make_executor'
      9: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/standard_middleware/show_help.rb:257:in `run'
      8: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:487:in `block in make_executor'
      7: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/standard_middleware/show_root_version.rb:90:in `run'
      6: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:487:in `block in make_executor'
      5: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/standard_middleware/handle_usage_errors.rb:62:in `run'
      4: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:487:in `block in make_executor'
      3: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/middleware.rb:90:in `run'
      2: /Users/kai/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/toys-core-0.8.0/lib/toys/cli.rb:446:in `block in perform_execution'
      1: /Users/kai/Programming/windborne/.toys/sims/generate.rb:7:in `run'
```

**Comment by dazuma** [comment]
Does this work?
```ruby
# generate.rb
def run
  require File.join context_directory, "config", "environment.rb"
  # Now you can access the Rails enviroment...
end
```

I realize there isn't much in the way of Rails-specific documentation (or conveniences). You're right that there should be.

**Comment by KMarshland** [comment]
It sure does. Thank you.
