### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#26]
```
> ./toys-dev test
**** Testing toys-core...
Your bundle is not complete. Install? (Y/n) 
Fetching gem metadata from https://rubygems.org/..................
Bundler::GemNotFound: You have requested:
  minitest ~> 5.14

The bundle currently has minitest locked at 5.13.0.
Try running `bundle update minitest`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
     42: /home/alex/Projects/ruby/toys/toys/bin/toys:30:in `<main>'
     41: /home/alex/Projects/ruby/toys/toys-core/lib/toys/cli.rb:447:in `run'
     40: /home/alex/Projects/ruby/toys/toys-core/lib/toys/errors.rb:91:in `capture_path'
     39: /home/alex/Projects/ruby/toys/toys-core/lib/toys/cli.rb:455:in `block in run'
     38: /home/alex/Projects/ruby/toys/toys-core/lib/toys/cli.rb:479:in `run_tool'
     37: /home/alex/Projects/ruby/toys/toys-core/lib/toys/tool.rb:1099:in `run_initializers'
     36: /home/alex/Projects/ruby/toys/toys-core/lib/toys/tool.rb:1099:in `each'
     35: /home/alex/Projects/ruby/toys/toys-core/lib/toys/tool.rb:1100:in `block in run_initializers'
     34: /home/alex/Projects/ruby/toys/toys-core/lib/toys/tool.rb:1100:in `instance_exec'
     33: /home/alex/Projects/ruby/toys/toys-core/lib/toys/standard_mixins/bundler.rb:77:in `block in <module:Bundler>'
     32: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:168:in `bundle'
     31: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:181:in `synchronize'
     30: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:181:in `synchronize'
     29: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:172:in `block in bundle'
     28: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:272:in `setup_bundle'
     27: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:275:in `rescue in setup_bundle'
     26: /home/alex/Projects/ruby/toys/toys-core/lib/toys/utils/gems.rb:300:in `install_bundle'
     25: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
     24: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     23: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
     22: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     21: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     20: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     19: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:255:in `install'
     18: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
     17: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:256:in `block in install'
     16: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli/install.rb:65:in `run'
     15: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
     14: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
     13: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
     12: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
     11: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
     10: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
      9: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/installer.rb:303:in `resolve_if_needed'
      8: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
      7: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
      6: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/definition.rb:258:in `resolve'
      5: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/resolver.rb:22:in `resolve'
      4: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/resolver.rb:49:in `start'
      3: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
      2: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/resolver.rb:258:in `each'
      1: /home/alex/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!'
Error during tool execution!
    Bundler::GemNotFound: You have requested:
  minitest ~> 5.14

The bundle currently has minitest locked at 5.13.0.
Try running `bundle update minitest`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
    while executing tool: "test"
    with arguments: []

> bundle update
Could not locate Gemfile
```

**Comment by dazuma** [comment]
cd into the `toys-core` subdirectory and `bundle update`. (And probably a good idea to do the same for the `toys` subdirectory.) Toys does not have a toplevel Gemfile. There are separate Gemfiles for the `toys` and `toys-core` directories.

**Comment by AlexWayfer** [comment]
Thank you, I understand, but I thought maybe you have a simple way to do this. So I've created #28.
