### ISSUE TITLE
Templates from gems

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#37]
Hello.

I've created (locally) gem with the code:

```ruby
# frozen_string_literal: true

require_relative 'benchmark_toys_template/version'

## Define tools for benchmark
module BenchmarkToysTemplate
  include Toys::Template

  on_expand do
    ## TODO: check it for `.toys.rb` and `.toys/.toys.rb`
    ROOT_DIR = caller_locations(1..1).first.path

    tool 'benchmark' do
      include :exec, exit_on_nonzero_status: true

      desc 'Benchmark code'

      def run
        require 'example_file'

        ExampleFile.new("#{ROOT_DIR}/benchmark/main.example.rb")
          .actualize_regular_file

        sh 'ruby benchmark/main.rb'
      end
    end
  end
end
```

And I'm trying to use it in a project:

```ruby
# Gemfile
gem 'benchmark_toys_template', path: '~/Projects/ruby/benchmark_toys_template'

# .toys/.toys.rb
require 'benchmark_toys_template'
expand BenchmarkToysTemplate
```

But I'm getting the error:

```
> toys benchmark                                                                                                                           13 Apr 23:12:48 
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Toys::ToolDefinitionError: Template not found: "benchmark"
     30: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `<main>'
     29: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `load'
     28: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-0.10.1/bin/toys:9:in `<top (required)>'
     27: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/cli.rb:423:in `run'
     26: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/errors.rb:90:in `capture'
     25: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/cli.rb:424:in `block in run'
     24: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:139:in `lookup'
     23: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:139:in `loop'
     22: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:140:in `block in lookup'
     21: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:160:in `lookup_specific'
     20: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:276:in `load_for_prefix'
     19: /home/alex/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
     18: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:280:in `block in load_for_prefix'
     17: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:280:in `each'
     16: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:285:in `block (2 levels) in load_for_prefix'
     15: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:388:in `load_validated_path'
     14: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:400:in `load_relevant_path'
     13: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:410:in `load_index_in'
     12: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/loader.rb:397:in `load_relevant_path'
     11: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/input_file.rb:26:in `evaluate'
     10: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/dsl/tool.rb:1694:in `prepare'
      9: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/input_file.rb:27:in `block in evaluate'
      8: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/errors.rb:70:in `capture_path'
      7: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/input_file.rb:29:in `block (2 levels) in evaluate'
      6: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/input_file.rb:29:in `eval'
      5: /home/alex/Projects/ruby/flame-cli/foo_bar/.toys/.toys.rb:in `__binding'
      4: /home/alex/Projects/ruby/flame-cli/foo_bar/.toys/.toys.rb:1:in `<module:M47007357845920__toys_rb>'
      3: /home/alex/Projects/ruby/flame-cli/foo_bar/.toys/.toys.rb:1:in `class_eval'
      2: /home/alex/Projects/ruby/flame-cli/foo_bar/.toys/.toys.rb:11:in `block in <module:M47007357845920__toys_rb>'
      1: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.1/lib/toys/dsl/tool.rb:449:in `expand'
Error while loading Toys config!
    Toys::ToolDefinitionError: Template not found: "benchmark"
    in config file: /home/alex/Projects/ruby/flame-cli/foo_bar/.toys/.toys.rb:11
```

**Comment by dazuma** [comment]
Hi Alex,

Sorry, I totally missed this. The error suggests that at some point (probably in `.toys/.toys.rb` line 11) you said `expand "benchmark"` or `expand :benchmark` rather than, as you listed in the source `expand BenchmarkToysTemplate`. Can you double-check that you are expanding the correct template module?

Also, looking at your template, it looks like you're trying to determine (`ROOT_DIR`) the directory containing the toys directory. You can get this info within the tool by calling `context_directory`. See https://dazuma.github.io/toys/gems/toys/v0.10.1/file.guide.html#The_context_directory

**Comment by AlexWayfer** [comment]
Sorry, I've tried to reproduce and got a error like `BenchmarkToysTemplate has no method initialize` (it was a module). That's strange, I read documentation. So, I've changed it to class and everything seems working.

Thank you for `context_directory` suggestion.

I'll re-open if something similar will be raised.
