### ISSUE TITLE
`:exit_on_nonzero_status` with parallel stopping

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#58]
Hello.

I have a such code (in tests):

```ruby
begin
  pid = spawn 'toys server start'
  # test
ensure
   system 'toys server stop'
end
```

And I'm getting such error:

```
[141119] Puma starting in cluster mode...
[141119] * Version 4.3.5 (ruby 2.6.6-p146), codename: Mysterious Traveller
[141119] * Min threads: 0, max threads: 4
[141119] * Environment: development
[141119] * Process workers: 1
[141119] * Phased restart available
[141119] * Listening on tcp://0.0.0.0:53951
[141119] Use Ctrl-C to stop
[141130] + Gemfile in context: /home/alex/Projects/ruby/flame-cli/foo_bar/Gemfile
I, [2020-08-02T03:29:08.979447 #141130]  INFO -- sentry: ** [Raven] Raven 3.0.0 configured not to capture errors: Not configured to send/capture in environment 'development'
[141119] - Worker 0 (pid: 141130) booted, phase: 0
get response
127.0.0.1 - - [02/Aug/2020:03:29:09 +0300] "GET / HTTP/1.1" 200 448 0.1043
[2020-08-02 03:29:09   ANY]  sh -c /home/alex/Projects/ruby/flame-cli/foo_bar/exe/setup/ruby.sh
[2020-08-02 03:29:11   ANY]  sh -c bundle\ exec\ pumactl\ stop
[141119] - Gracefully shutting down workers...
NoMethodError: undefined method `zero?' for nil:NilClass
     31: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `<main>'
     30: /home/alex/.rbenv/versions/2.6.6/bin/toys:23:in `load'
     29: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-0.10.5/bin/toys:11:in `<top (required)>'
     28: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:426:in `run'
     27: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/errors.rb:70:in `capture_path'
     26: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:434:in `block in run'
     25: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:466:in `run_tool'
     24: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:490:in `execute_tool_in_context'
     23: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:490:in `catch'
     22: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:491:in `block in execute_tool_in_context'
     21: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:522:in `block in make_executor'
     20: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/standard_middleware/show_help.rb:234:in `run'
     19: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:522:in `block in make_executor'
     18: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/standard_middleware/show_root_version.rb:67:in `run'
     17: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:522:in `block in make_executor'
     16: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/standard_middleware/handle_usage_errors.rb:39:in `run'
     15: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/cli.rb:480:in `block in execute_tool_in_context'
     14: /home/alex/Projects/ruby/flame_server_toys/lib/flame_server_toys/template/start.rb:12:in `block (3 levels) in <class:Start>'
     13: /home/alex/Projects/ruby/flame_server_toys/lib/flame_server_toys/template/_base.rb:57:in `server'
     12: /home/alex/Projects/ruby/flame_server_toys/lib/flame_server_toys/template/_base.rb:67:in `web_server'
     11: /home/alex/Projects/ruby/flame_server_toys/lib/flame_server_toys/template/_base.rb:71:in `puma_command'
     10: /home/alex/Projects/ruby/flame_server_toys/lib/flame_server_toys/template/_base.rb:31:in `sh'
      9: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/standard_mixins/exec.rb:664:in `sh'
      8: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:397:in `sh'
      7: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:262:in `exec'
      6: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:893:in `execute'
      5: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:736:in `result'
      4: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:736:in `tap'
      3: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:736:in `block in result'
      2: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/standard_mixins/exec.rb:711:in `block in _interpret_e'
      1: /home/alex/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/toys-core-0.10.5/lib/toys/utils/exec.rb:858:in `error?'
Error during tool execution!
    NoMethodError: undefined method `zero?' for nil:NilClass
    while executing tool: "server start"
    with arguments: []
```

So, as I understand, there is no exit code for processes stopped from outside and we should catch this.

Like, I want to get errors (aborts) when there are errors on direct call (`server start`), but I don't care of `start`s result when I call `server stop`.

**Comment by dazuma** [comment]
Hmm, this is very surprising to me. My understanding is that there should _always_ be an exit code for a process, even if it is terminated from the outside (e.g. by sending a signal, which I assume is what is going on here with Puma.) Let me try to reproduce this.

**Comment by dazuma** [comment]
Well, looks like I was wrong. Processes have no exit status if they are terminated by uncaught signal. Okay, I'll need to adjust the various handling mechanisms to include this as a separate case. Thanks for the report!
